Booking controller
Mo-og/intellistart-java-2022-debuggers pull request #43
Opened 2022-10-13 21:34 UTC by Ewentualnie

add new BookingController

2022-10-13 21:35 UTC, Mo-og commented
|File|Coverage [26.05%]|:green_apple:|
|:-|:-:|:-:|
|[BookingService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/a2cdf8f6d48b950f96a4059ebc03e36f51d5ab7a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingService.java)|48.89%|:green_apple:|
|[BookingController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/a2cdf8f6d48b950f96a4059ebc03e36f51d5ab7a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FBookingController.java)|12.5%|:green_apple:|
|[Candidate.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/a2cdf8f6d48b950f96a4059ebc03e36f51d5ab7a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidate.java)|11.54%|:green_apple:|

|Total Project Coverage|22.65%|:green_apple:|
|:-|:-:|:-:|

2022-10-14 09:17 UTC, olesiayakovenko commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/BookingController.java
> +   */
Probably should add @Autowired here

2022-10-14 09:27 UTC, olesiayakovenko approved these changes
Ok

2022-10-14 09:27 UTC, olesiayakovenko commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/BookingController.java
> +  public BookingController(BookingService bookingService) {
Probably should add @Autowired here

2022-10-14 12:53 UTC, Mo-og commented
You need to return Booking object from controller instead of "true"

2022-10-14 13:07 UTC, Mo-og requested changes

2022-10-14 13:07 UTC, Mo-og commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/BookingController.java
> +    booking.setFrom(LocalTime.now());
should be ...setFrom(updatedBooking.getFrom()) and so on

2022-10-14 13:07 UTC, Mo-og commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/BookingController.java
> +    Booking booking = bookingService.getBooking(bookingId);
Must be in service, not controller

2022-10-14 13:07 UTC, Mo-og commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/BookingController.java
> +    return true;
Make sure booking changes are saved and return it instead of boolean

2022-10-14 13:07 UTC, Mo-og commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/BookingController.java
> +    return true;
simplify to "return bookingService.removeBooking(bookingId);"
probably shoud return ResponseEntity.ok() or similar instead of boolean

2022-10-14 13:07 UTC, Mo-og commented on src/main/java/com/intellias/intellistart/interviewplanning/services/BookingService.java
> +  public Booking createBooking(LocalTime from, LocalTime to, CandidateTimeSlot candidateSlot,
We'll probably get a booking object instead of separate fields from, to...

2022-10-14 19:44 UTC, Mo-og commented
|File|Coverage [14.62%]|:green_apple:|
|:-|:-:|:-:|
|[BookingService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/0df5129db936e23b4098f36286068061ac2c04ac/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingService.java)|41.94%|:green_apple:|
|[BookingController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/0df5129db936e23b4098f36286068061ac2c04ac/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FBookingController.java)|29.27%|:green_apple:|
|[Candidate.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/0df5129db936e23b4098f36286068061ac2c04ac/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidate.java)|11.54%|:green_apple:|
|[Booking.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/0df5129db936e23b4098f36286068061ac2c04ac/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|8.04%|:x:|

|Total Project Coverage|20.38%|:green_apple:|
|:-|:-:|:-:|

2022-10-14 19:57 UTC, closed without merging