:boom: add possibility update timeslot
Mo-og/intellistart-java-2022-debuggers pull request #59
Opened 2022-10-22 09:58 UTC by Ewentualnie

add possibility update timeslot:
`POST "/interviewers/{interviewerId}/slots/{slotId}"`

2022-10-22 09:58 UTC, Mo-og commented
|File|Coverage [14.17%]|:green_apple:|
|:-|:-:|:-:|
|[SlotController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f6b841bd25a1b9be9b7741dd71b3580fb810d808/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FSlotController.java)|70.83%|:green_apple:|
|[InterviewerService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f6b841bd25a1b9be9b7741dd71b3580fb810d808/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|0%|:x:|

|Total Project Coverage|33.31%|:green_apple:|
|:-|:-:|:-:|

2022-10-23 10:16 UTC, Mo-og commented
|File|Coverage [8.85%]|:x:|
|:-|:-:|:-:|
|[SlotController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ae5812b61dc81b5bec704948afd91e032c4e1cd0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FSlotController.java)|60.61%|:green_apple:|
|[CandidateService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ae5812b61dc81b5bec704948afd91e032c4e1cd0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCandidateService.java)|0%|:x:|
|[InterviewerService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ae5812b61dc81b5bec704948afd91e032c4e1cd0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|0%|:x:|

|Total Project Coverage|33.31%|:green_apple:|
|:-|:-:|:-:|

2022-10-23 16:09 UTC, Mo-og requested changes
minor code cleanup

2022-10-23 16:09 UTC, Mo-og commented on src/main/java/com/intellias/intellistart/interviewplanning/services/CandidateService.java
> +  public User getUserById(Long id) {
Should not be renamed. It is better to preserve same method namings for service interfaces

2022-10-23 16:09 UTC, Mo-og commented on src/main/java/com/intellias/intellistart/interviewplanning/services/InterviewerService.java
> +  public InterviewerTimeSlot updateSlot(long interviewerId, long slotId,
long -> Long

2022-10-23 16:47 UTC, Mo-og commented
|File|Coverage [8.97%]|:x:|
|:-|:-:|:-:|
|[SlotController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f79b9e76199769365c3191f1dec14c52ba713154/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FSlotController.java)|58.82%|:green_apple:|
|[CandidateService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f79b9e76199769365c3191f1dec14c52ba713154/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCandidateService.java)|0%|:x:|
|[InterviewerService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f79b9e76199769365c3191f1dec14c52ba713154/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|0%|:x:|

|Total Project Coverage|33.37%|:green_apple:|
|:-|:-:|:-:|

2022-10-23 16:47 UTC, Ewentualnie commented
add changes

2022-10-23 16:48 UTC, Mo-og approved these changes

2022-10-23 16:51 UTC, merged