:monocle_face: Booking Limit implements
Mo-og/intellistart-java-2022-debuggers pull request #63
Opened 2022-10-27 21:53 UTC by Ewentualnie

2022-10-27 21:53 UTC, Mo-og commented
|File|Coverage [47.6%]|:green_apple:|
|:-|:-:|:-:|
|[BookingLimitController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6524a871e957c509c7d18dcd5b4383eba6240761/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FBookingLimitController.java)|100%|:green_apple:|
|[UserService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6524a871e957c509c7d18dcd5b4383eba6240761/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|100%|:green_apple:|
|[BookingLimit.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6524a871e957c509c7d18dcd5b4383eba6240761/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBookingLimit.java)|55.81%|:green_apple:|
|[UserController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6524a871e957c509c7d18dcd5b4383eba6240761/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FUserController.java)|54.05%|:green_apple:|
|[WeekEditException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6524a871e957c509c7d18dcd5b4383eba6240761/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FWeekEditException.java)|45.45%|:green_apple:|
|[BookingController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6524a871e957c509c7d18dcd5b4383eba6240761/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FBookingController.java)|0%|:x:|
|[BookingLimitService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6524a871e957c509c7d18dcd5b4383eba6240761/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingLimitService.java)|0%|:x:|

|Total Project Coverage|33.85%|:green_apple:|
|:-|:-:|:-:|

2022-10-29 17:37 UTC, Mo-og commented
|File|Coverage [93.15%]|:green_apple:|
|:-|:-:|:-:|
|[WeekEditException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/0ba5fe8d47236e9eb23048a5d490774d204294ec/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FWeekEditException.java)|100%|:green_apple:|
|[BookingLimitController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/0ba5fe8d47236e9eb23048a5d490774d204294ec/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FBookingLimitController.java)|100%|:green_apple:|
|[BookingController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/0ba5fe8d47236e9eb23048a5d490774d204294ec/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FBookingController.java)|100%|:green_apple:|
|[UserController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/0ba5fe8d47236e9eb23048a5d490774d204294ec/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FUserController.java)|100%|:green_apple:|
|[UserService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/0ba5fe8d47236e9eb23048a5d490774d204294ec/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/0ba5fe8d47236e9eb23048a5d490774d204294ec/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingLimitService.java)|100%|:green_apple:|
|[BookingLimit.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/0ba5fe8d47236e9eb23048a5d490774d204294ec/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBookingLimit.java)|72.09%|:green_apple:|
|[BookingLimitResponse.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/0ba5fe8d47236e9eb23048a5d490774d204294ec/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2Fdto%2FBookingLimitResponse.java)|68.29%|:green_apple:|

|Total Project Coverage|91.55%|:green_apple:|
|:-|:-:|:-:|

2022-10-29 18:19 UTC, Mo-og requested changes

2022-10-29 18:19 UTC, Mo-og commented on src/main/java/com/intellias/intellistart/interviewplanning/services/BookingLimitService.java
> +    return bookingLimitRepository.findByInterviewerIdAndWeekNum(interviewerId, weekNum);
If nothing was found service should first check if interviewer had any limits set before given weekNum. If they had then return that limit or set that limit to current week and then return.

2022-10-29 18:19 UTC, Mo-og commented on src/main/java/com/intellias/intellistart/interviewplanning/services/BookingLimitService.java
> +  public BookingLimit getBookingLimit(Long interviewerId, Integer weekNum) {
Should be renamed to smth like `getBookingLimitByInterviewerIdAndWeekNum()` or `obtainBookinLimit()` to differ from getters

2022-10-29 18:19 UTC, Mo-og commented on src/main/java/com/intellias/intellistart/interviewplanning/services/BookingLimitService.java
> +  public List<BookingLimit> getWeekBookingLimits(Integer weekNum) {
Should be renamed to smth like `getBookingLimitsByWeekNum`

2022-10-29 18:19 UTC, Mo-og commented on src/main/java/com/intellias/intellistart/interviewplanning/services/BookingLimitService.java
> +  public BookingLimit setBookingLimit(Integer limit, Long interviewerId, Integer weekNum) {
Should be renamed to smth like `saveBookingLimit` to differ from setters

2022-10-29 18:19 UTC, Mo-og commented on src/main/java/com/intellias/intellistart/interviewplanning/services/BookingLimitService.java
> +  public BookingLimitResponse getUserWeekBookingLimit(Long interviewerId, Integer weekNum) {
Should be renamed

2022-10-29 18:19 UTC, Mo-og commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/BookingLimitController.java
> +  @GetMapping("/interviewers/bookingLimits/week/user")
Url should be `/interviewers/{interviewerId}/bookingLimits/{weekId}`

2022-10-29 18:25 UTC, Ewentualnie commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/BookingLimitController.java
> +  @GetMapping("/interviewers/bookingLimits/week/user")
got it

2022-10-29 21:13 UTC, Mo-og commented
|File|Coverage [94.51%]|:green_apple:|
|:-|:-:|:-:|
|[BookingLimitRequest.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f79070b05f1eef7da9db13c5426b462cf12ecd93/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2Fdto%2FBookingLimitRequest.java)|100%|:green_apple:|
|[WeekEditException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f79070b05f1eef7da9db13c5426b462cf12ecd93/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FWeekEditException.java)|100%|:green_apple:|
|[BookingController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f79070b05f1eef7da9db13c5426b462cf12ecd93/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FBookingController.java)|100%|:green_apple:|
|[UserController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f79070b05f1eef7da9db13c5426b462cf12ecd93/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FUserController.java)|100%|:green_apple:|
|[UserService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f79070b05f1eef7da9db13c5426b462cf12ecd93/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f79070b05f1eef7da9db13c5426b462cf12ecd93/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingLimitService.java)|100%|:green_apple:|
|[BookingLimitController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f79070b05f1eef7da9db13c5426b462cf12ecd93/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FBookingLimitController.java)|73.91%|:green_apple:|
|[BookingLimit.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f79070b05f1eef7da9db13c5426b462cf12ecd93/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBookingLimit.java)|72.09%|:green_apple:|

|Total Project Coverage|91.76%|:green_apple:|
|:-|:-:|:-:|

2022-10-29 21:19 UTC, Mo-og commented
|File|Coverage [94.51%]|:green_apple:|
|:-|:-:|:-:|
|[BookingLimitRequest.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7b65c705bbf930fb0a05a59013e8954af644cf5a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2Fdto%2FBookingLimitRequest.java)|100%|:green_apple:|
|[WeekEditException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7b65c705bbf930fb0a05a59013e8954af644cf5a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FWeekEditException.java)|100%|:green_apple:|
|[BookingController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7b65c705bbf930fb0a05a59013e8954af644cf5a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FBookingController.java)|100%|:green_apple:|
|[UserController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7b65c705bbf930fb0a05a59013e8954af644cf5a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FUserController.java)|100%|:green_apple:|
|[UserService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7b65c705bbf930fb0a05a59013e8954af644cf5a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7b65c705bbf930fb0a05a59013e8954af644cf5a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingLimitService.java)|100%|:green_apple:|
|[BookingLimitController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7b65c705bbf930fb0a05a59013e8954af644cf5a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FBookingLimitController.java)|73.91%|:green_apple:|
|[BookingLimit.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7b65c705bbf930fb0a05a59013e8954af644cf5a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBookingLimit.java)|72.09%|:green_apple:|

|Total Project Coverage|91.76%|:green_apple:|
|:-|:-:|:-:|

2022-10-29 21:20 UTC, Ewentualnie commented on src/main/java/com/intellias/intellistart/interviewplanning/models/dto/BookingLimitResponse.java
> +
for what?

2022-10-29 21:22 UTC, Mo-og commented
|File|Coverage [94.51%]|:green_apple:|
|:-|:-:|:-:|
|[BookingLimitRequest.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f3c92217a159f7918a59eb4111aaab9b4f90638e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2Fdto%2FBookingLimitRequest.java)|100%|:green_apple:|
|[WeekEditException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f3c92217a159f7918a59eb4111aaab9b4f90638e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FWeekEditException.java)|100%|:green_apple:|
|[BookingController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f3c92217a159f7918a59eb4111aaab9b4f90638e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FBookingController.java)|100%|:green_apple:|
|[UserController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f3c92217a159f7918a59eb4111aaab9b4f90638e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FUserController.java)|100%|:green_apple:|
|[UserService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f3c92217a159f7918a59eb4111aaab9b4f90638e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f3c92217a159f7918a59eb4111aaab9b4f90638e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingLimitService.java)|100%|:green_apple:|
|[BookingLimitController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f3c92217a159f7918a59eb4111aaab9b4f90638e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FBookingLimitController.java)|73.91%|:green_apple:|
|[BookingLimit.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f3c92217a159f7918a59eb4111aaab9b4f90638e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBookingLimit.java)|72.09%|:green_apple:|

|Total Project Coverage|91.76%|:green_apple:|
|:-|:-:|:-:|

2022-10-30 10:54 UTC, Mo-og commented
|File|Coverage [92.25%]|:green_apple:|
|:-|:-:|:-:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7e6b7b503afddcc627a3d0e234b8c083f1795ec5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[WeekEditException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7e6b7b503afddcc627a3d0e234b8c083f1795ec5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FWeekEditException.java)|100%|:green_apple:|
|[BookingLimitController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7e6b7b503afddcc627a3d0e234b8c083f1795ec5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FBookingLimitController.java)|100%|:green_apple:|
|[BookingController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7e6b7b503afddcc627a3d0e234b8c083f1795ec5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FBookingController.java)|100%|:green_apple:|
|[UserController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7e6b7b503afddcc627a3d0e234b8c083f1795ec5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FUserController.java)|100%|:green_apple:|
|[UserService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7e6b7b503afddcc627a3d0e234b8c083f1795ec5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7e6b7b503afddcc627a3d0e234b8c083f1795ec5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingLimitService.java)|100%|:green_apple:|
|[BookingLimit.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7e6b7b503afddcc627a3d0e234b8c083f1795ec5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBookingLimit.java)|72.09%|:green_apple:|
|[BookingLimitRequest.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7e6b7b503afddcc627a3d0e234b8c083f1795ec5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2Fdto%2FBookingLimitRequest.java)|69.35%|:green_apple:|
|[BookingLimitException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7e6b7b503afddcc627a3d0e234b8c083f1795ec5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FBookingLimitException.java)|0%|:x:|

|Total Project Coverage|90.79%|:green_apple:|
|:-|:-:|:-:|

2022-10-30 15:08 UTC, Mo-og approved these changes

2022-10-30 15:08 UTC, Mo-og commented on src/main/java/com/intellias/intellistart/interviewplanning/models/dto/BookingLimitRequest.java
> +public class BookingLimitRequest {
Why name is not BookingLimitDto ?

2022-10-30 15:08 UTC, Mo-og commented on src/main/java/com/intellias/intellistart/interviewplanning/services/BookingLimitService.java
> +      throw new UserNotFoundException(interviewerId + "");
> ~Replace `interviewerId + ""` with `interviewerId.toString()`~
> 
> Use InterviewerNotFoundException instead

Still there

2022-10-30 15:08 UTC, Mo-og commented on src/main/java/com/intellias/intellistart/interviewplanning/services/BookingLimitService.java
> +    return bookingLimitRepository.findByInterviewerIdAndWeekNum(interviewerId, weekNum);
Still there, but can be new issue

2022-10-30 15:08 UTC, Mo-og commented on src/test/java/com/intellias/intellistart/interviewplanning/services/BookingLimitServiceTest.java
> +    lenient().when(userRepository.existsById(notExistingUserId))
Are you sure lentient is needed?

2022-10-30 17:52 UTC, merged