Group exceptions by status
Mo-og/intellistart-java-2022-debuggers pull request #81
Opened 2022-11-08 13:20 UTC by Ewentualnie

2022-11-08 13:21 UTC, Mo-og commented
|File|Coverage [94.02%]|:green_apple:|
|:-|:-:|:-:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/96978dcb636770e0f5c7201d4b44c4a8426c8721/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[NotFoundException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/96978dcb636770e0f5c7201d4b44c4a8426c8721/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FNotFoundException.java)|100%|:green_apple:|
|[BadRequestException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/96978dcb636770e0f5c7201d4b44c4a8426c8721/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FBadRequestException.java)|100%|:green_apple:|
|[PeriodValidator.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/96978dcb636770e0f5c7201d4b44c4a8426c8721/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fvalidators%2FPeriodValidator.java)|100%|:green_apple:|
|[UserService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/96978dcb636770e0f5c7201d4b44c4a8426c8721/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|100%|:green_apple:|
|[CandidateService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/96978dcb636770e0f5c7201d4b44c4a8426c8721/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCandidateService.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/96978dcb636770e0f5c7201d4b44c4a8426c8721/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingLimitService.java)|100%|:green_apple:|
|[CoordinatorService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/96978dcb636770e0f5c7201d4b44c4a8426c8721/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCoordinatorService.java)|100%|:green_apple:|
|[BookingService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/96978dcb636770e0f5c7201d4b44c4a8426c8721/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingService.java)|93.68%|:green_apple:|
|[InterviewerSlotValidator.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/96978dcb636770e0f5c7201d4b44c4a8426c8721/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fvalidators%2FInterviewerSlotValidator.java)|81.48%|:green_apple:|
|[InterviewerService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/96978dcb636770e0f5c7201d4b44c4a8426c8721/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|65.99%|:green_apple:|

|Total Project Coverage|69.14%|:green_apple:|
|:-|:-:|:-:|

2022-11-08 16:14 UTC, Mo-og requested changes
Last PR was 75% project coverage. Now it is 69%. Should be increased

2022-11-08 16:14 UTC, Mo-og commented on src/test/java/com/intellias/intellistart/interviewplanning/services/InterviewerServiceTest.java
> -  @Test
Why removed?

2022-11-08 16:20 UTC, olesiayakovenko commented
Why were the changes from the previous pull request removed?

2022-11-08 16:29 UTC, Ewentualnie commented on src/test/java/com/intellias/intellistart/interviewplanning/services/InterviewerServiceTest.java
> -  @Test
mistake while merge =(

2022-11-08 16:32 UTC, Ewentualnie commented
> 

mistake while merge local branches =(
add removed code after meet

2022-11-08 18:50 UTC, Mo-og commented
|File|Coverage [98.63%]|:green_apple:|
|:-|:-:|:-:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7e557021a9bdde17fc226185bcc15414c23af3a0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[NotFoundException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7e557021a9bdde17fc226185bcc15414c23af3a0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FNotFoundException.java)|100%|:green_apple:|
|[InvalidInputException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7e557021a9bdde17fc226185bcc15414c23af3a0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidInputException.java)|100%|:green_apple:|
|[PeriodValidator.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7e557021a9bdde17fc226185bcc15414c23af3a0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fvalidators%2FPeriodValidator.java)|100%|:green_apple:|
|[UserService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7e557021a9bdde17fc226185bcc15414c23af3a0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|100%|:green_apple:|
|[CandidateService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7e557021a9bdde17fc226185bcc15414c23af3a0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCandidateService.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7e557021a9bdde17fc226185bcc15414c23af3a0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingLimitService.java)|100%|:green_apple:|
|[CoordinatorService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7e557021a9bdde17fc226185bcc15414c23af3a0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCoordinatorService.java)|100%|:green_apple:|
|[InterviewerService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7e557021a9bdde17fc226185bcc15414c23af3a0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|97.96%|:green_apple:|
|[BookingService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7e557021a9bdde17fc226185bcc15414c23af3a0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingService.java)|93.68%|:green_apple:|
|[InterviewerSlotValidator.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/7e557021a9bdde17fc226185bcc15414c23af3a0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fvalidators%2FInterviewerSlotValidator.java)|81.48%|:green_apple:|

|Total Project Coverage|73.26%|:green_apple:|
|:-|:-:|:-:|

2022-11-08 19:48 UTC, Mo-og commented
|File|Coverage [98.67%]|:green_apple:|
|:-|:-:|:-:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/426893b9c089285a197a7fb53fd8a50cbf298a08/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[NotFoundException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/426893b9c089285a197a7fb53fd8a50cbf298a08/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FNotFoundException.java)|100%|:green_apple:|
|[InvalidInputException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/426893b9c089285a197a7fb53fd8a50cbf298a08/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidInputException.java)|100%|:green_apple:|
|[PeriodValidator.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/426893b9c089285a197a7fb53fd8a50cbf298a08/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fvalidators%2FPeriodValidator.java)|100%|:green_apple:|
|[UserService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/426893b9c089285a197a7fb53fd8a50cbf298a08/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|100%|:green_apple:|
|[CandidateService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/426893b9c089285a197a7fb53fd8a50cbf298a08/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCandidateService.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/426893b9c089285a197a7fb53fd8a50cbf298a08/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingLimitService.java)|100%|:green_apple:|
|[CoordinatorService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/426893b9c089285a197a7fb53fd8a50cbf298a08/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCoordinatorService.java)|100%|:green_apple:|
|[InterviewerService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/426893b9c089285a197a7fb53fd8a50cbf298a08/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|97.96%|:green_apple:|
|[BookingService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/426893b9c089285a197a7fb53fd8a50cbf298a08/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingService.java)|93.68%|:green_apple:|
|[InterviewerSlotValidator.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/426893b9c089285a197a7fb53fd8a50cbf298a08/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fvalidators%2FInterviewerSlotValidator.java)|81.48%|:green_apple:|

|Total Project Coverage|77.01%|:green_apple:|
|:-|:-:|:-:|

2022-11-09 14:58 UTC, Mo-og reviewed
Code is fine. @olesiayakovenko are all changes present?

2022-11-09 14:58 UTC, Mo-og commented on src/test/java/com/intellias/intellistart/interviewplanning/exceptions/InvalidInputExceptionTest.java
> +  void invalidBoundariesTest() {
We should test that services (or validators etc.) throw exceptions when they are supposed to. Unit tests for exceptions themselves is too much, I think.

2022-11-09 15:07 UTC, Mo-og approved these changes

2022-11-09 16:14 UTC, olesiayakovenko approved these changes

2022-11-09 16:18 UTC, merged