Repository refactoring
Mo-og/intellistart-java-2022-debuggers pull request #85
Opened 2022-11-11 13:07 UTC by Ewentualnie

2022-11-11 13:08 UTC, Mo-og commented
|File|Coverage [88.97%]|:green_apple:|
|:-|:-:|:-:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b57ff1ecf97463f3b3a6737671bf0eedc3d689ae/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b57ff1ecf97463f3b3a6737671bf0eedc3d689ae/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingLimitService.java)|95.24%|:green_apple:|
|[BookingLimit.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b57ff1ecf97463f3b3a6737671bf0eedc3d689ae/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBookingLimit.java)|83.67%|:green_apple:|
|[NotFoundException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b57ff1ecf97463f3b3a6737671bf0eedc3d689ae/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FNotFoundException.java)|45.61%|:green_apple:|

|Total Project Coverage|56.53%|:green_apple:|
|:-|:-:|:-:|

2022-11-11 13:50 UTC, Mo-og commented on src/main/java/com/intellias/intellistart/interviewplanning/exceptions/NotFoundException.java
> +        String.format(": interviewer %d does not have ani booking limit on week %d",
ani -> any

2022-11-11 13:50 UTC, Mo-og commented on src/test/java/com/intellias/intellistart/interviewplanning/services/BookingLimitServiceTest.java
>    void testSetBookingNewBooking() {
Actually misleading method names
`…SetBookingNewBooking…`->`…UpdateBookingLimit…` or smth similar

2022-11-12 07:18 UTC, Mo-og commented
|File|Coverage [70.09%]|:green_apple:|
|:-|:-:|:-:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/5a5f7a1ef59c43c511f0447777af14bbe528011e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/5a5f7a1ef59c43c511f0447777af14bbe528011e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingLimitService.java)|95.24%|:green_apple:|
|[BookingLimit.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/5a5f7a1ef59c43c511f0447777af14bbe528011e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBookingLimit.java)|83.67%|:green_apple:|
|[BookingDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/5a5f7a1ef59c43c511f0447777af14bbe528011e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingDto.java)|62.88%|:green_apple:|
|[InterviewerSlotDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/5a5f7a1ef59c43c511f0447777af14bbe528011e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerSlotDto.java)|57.91%|:green_apple:|
|[NotFoundException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/5a5f7a1ef59c43c511f0447777af14bbe528011e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FNotFoundException.java)|45.61%|:green_apple:|

|Total Project Coverage|56.03%|:green_apple:|
|:-|:-:|:-:|

2022-11-12 08:47 UTC, Mo-og commented
|File|Coverage [70.09%]|:green_apple:|
|:-|:-:|:-:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/0fc880e56a21dcb56a2038d396c43f5cdeee86e2/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/0fc880e56a21dcb56a2038d396c43f5cdeee86e2/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingLimitService.java)|95.24%|:green_apple:|
|[BookingLimit.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/0fc880e56a21dcb56a2038d396c43f5cdeee86e2/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBookingLimit.java)|83.67%|:green_apple:|
|[BookingDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/0fc880e56a21dcb56a2038d396c43f5cdeee86e2/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingDto.java)|62.88%|:green_apple:|
|[InterviewerSlotDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/0fc880e56a21dcb56a2038d396c43f5cdeee86e2/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerSlotDto.java)|57.91%|:green_apple:|
|[NotFoundException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/0fc880e56a21dcb56a2038d396c43f5cdeee86e2/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FNotFoundException.java)|45.61%|:green_apple:|

|Total Project Coverage|56.11%|:green_apple:|
|:-|:-:|:-:|

2022-11-12 10:17 UTC, olesiayakovenko commented on src/main/java/com/intellias/intellistart/interviewplanning/services/BookingLimitService.java
> +        .orElse(new BookingLimit(interviewerId));
In any case a new BookingLimit will be created (regardless of Optional.isPresent() value). To avoid this, you should use orElseGet (will only call the given function when the Optional.isPresent() == false).

2022-11-12 10:17 UTC, olesiayakovenko commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/dto/InterviewerSlotDto.java
> +@Setter
@Data has getters and setters

2022-11-12 10:40 UTC, Mo-og commented
|File|Coverage [70.69%]|:green_apple:|
|:-|:-:|:-:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/a38863f6b38f270a962b459cfb76722b6e1c891f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/a38863f6b38f270a962b459cfb76722b6e1c891f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingLimitService.java)|95.24%|:green_apple:|
|[BookingLimit.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/a38863f6b38f270a962b459cfb76722b6e1c891f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBookingLimit.java)|83.67%|:green_apple:|
|[BookingDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/a38863f6b38f270a962b459cfb76722b6e1c891f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingDto.java)|62.88%|:green_apple:|
|[InterviewerSlotDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/a38863f6b38f270a962b459cfb76722b6e1c891f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerSlotDto.java)|57.91%|:green_apple:|
|[NotFoundException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/a38863f6b38f270a962b459cfb76722b6e1c891f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FNotFoundException.java)|57.89%|:green_apple:|

|Total Project Coverage|56.99%|:green_apple:|
|:-|:-:|:-:|

2022-11-12 10:41 UTC, olesiayakovenko commented on src/test/java/com/intellias/intellistart/interviewplanning/services/UserServiceTest.java
> +//:white_check_mark: cover UserController with test to 63%
Remove

2022-11-12 12:12 UTC, Mo-og commented
|File|Coverage [69.83%]|:green_apple:|
|:-|:-:|:-:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6e9cf45e9c3e11e9ebfd51af7c68b67eae8cf3ac/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6e9cf45e9c3e11e9ebfd51af7c68b67eae8cf3ac/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingLimitService.java)|89.66%|:green_apple:|
|[BookingLimit.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6e9cf45e9c3e11e9ebfd51af7c68b67eae8cf3ac/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBookingLimit.java)|71.43%|:green_apple:|
|[BookingDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6e9cf45e9c3e11e9ebfd51af7c68b67eae8cf3ac/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingDto.java)|62.88%|:green_apple:|
|[InterviewerSlotDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6e9cf45e9c3e11e9ebfd51af7c68b67eae8cf3ac/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerSlotDto.java)|57.91%|:green_apple:|
|[NotFoundException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6e9cf45e9c3e11e9ebfd51af7c68b67eae8cf3ac/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FNotFoundException.java)|57.89%|:green_apple:|

|Total Project Coverage|56.81%|:green_apple:|
|:-|:-:|:-:|

2022-11-12 12:14 UTC, Mo-og commented
|File|Coverage [69.83%]|:green_apple:|
|:-|:-:|:-:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/aaa6ced05bd0520d7a0c5cb77731ff8aaf78a3f9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/aaa6ced05bd0520d7a0c5cb77731ff8aaf78a3f9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingLimitService.java)|89.66%|:green_apple:|
|[BookingLimit.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/aaa6ced05bd0520d7a0c5cb77731ff8aaf78a3f9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBookingLimit.java)|71.43%|:green_apple:|
|[BookingDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/aaa6ced05bd0520d7a0c5cb77731ff8aaf78a3f9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingDto.java)|62.88%|:green_apple:|
|[InterviewerSlotDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/aaa6ced05bd0520d7a0c5cb77731ff8aaf78a3f9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerSlotDto.java)|57.91%|:green_apple:|
|[NotFoundException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/aaa6ced05bd0520d7a0c5cb77731ff8aaf78a3f9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FNotFoundException.java)|57.89%|:green_apple:|

|Total Project Coverage|56.81%|:green_apple:|
|:-|:-:|:-:|

2022-11-12 12:18 UTC, Mo-og commented
|File|Coverage [70.55%]|:green_apple:|
|:-|:-:|:-:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/87eb8d1c2e29d4ecfd4a8c76f65b88ac1565e111/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/87eb8d1c2e29d4ecfd4a8c76f65b88ac1565e111/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingLimitService.java)|89.66%|:green_apple:|
|[Booking.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/87eb8d1c2e29d4ecfd4a8c76f65b88ac1565e111/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|76.39%|:green_apple:|
|[BookingLimit.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/87eb8d1c2e29d4ecfd4a8c76f65b88ac1565e111/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBookingLimit.java)|71.43%|:green_apple:|
|[BookingDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/87eb8d1c2e29d4ecfd4a8c76f65b88ac1565e111/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingDto.java)|62.88%|:green_apple:|
|[InterviewerSlotDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/87eb8d1c2e29d4ecfd4a8c76f65b88ac1565e111/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerSlotDto.java)|57.91%|:green_apple:|
|[NotFoundException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/87eb8d1c2e29d4ecfd4a8c76f65b88ac1565e111/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FNotFoundException.java)|57.89%|:green_apple:|

|Total Project Coverage|56.97%|:green_apple:|
|:-|:-:|:-:|

2022-11-12 16:01 UTC, Mo-og commented
|File|Coverage [68.49%]|:green_apple:|
|:-|:-:|:-:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f0c7f84db578d58019e3d9d549c69bb8ab69cdc6/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f0c7f84db578d58019e3d9d549c69bb8ab69cdc6/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingLimitService.java)|89.66%|:green_apple:|
|[Booking.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f0c7f84db578d58019e3d9d549c69bb8ab69cdc6/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|76.39%|:green_apple:|
|[BookingLimit.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f0c7f84db578d58019e3d9d549c69bb8ab69cdc6/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBookingLimit.java)|71.43%|:green_apple:|
|[InterviewerSlotValidator.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f0c7f84db578d58019e3d9d549c69bb8ab69cdc6/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fvalidators%2FInterviewerSlotValidator.java)|62.96%|:green_apple:|
|[BookingDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f0c7f84db578d58019e3d9d549c69bb8ab69cdc6/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingDto.java)|62.88%|:green_apple:|
|[InterviewerService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f0c7f84db578d58019e3d9d549c69bb8ab69cdc6/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|59.62%|:green_apple:|
|[InterviewerSlotDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f0c7f84db578d58019e3d9d549c69bb8ab69cdc6/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerSlotDto.java)|57.91%|:green_apple:|
|[NotFoundException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f0c7f84db578d58019e3d9d549c69bb8ab69cdc6/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FNotFoundException.java)|44.59%|:green_apple:|

|Total Project Coverage|56.87%|:green_apple:|
|:-|:-:|:-:|

2022-11-13 16:05 UTC, Mo-og commented
|File|Coverage [78.59%]|:green_apple:|
|:-|:-:|:-:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6716c0001471ecb23830abc2de668d5dc9bb0fbb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[WeekController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6716c0001471ecb23830abc2de668d5dc9bb0fbb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FWeekController.java)|100%|:green_apple:|
|[SlotController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6716c0001471ecb23830abc2de668d5dc9bb0fbb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FSlotController.java)|100%|:green_apple:|
|[WeekServiceImp.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6716c0001471ecb23830abc2de668d5dc9bb0fbb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FWeekServiceImp.java)|100%|:green_apple:|
|[InterviewerService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6716c0001471ecb23830abc2de668d5dc9bb0fbb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|97.62%|:green_apple:|
|[CoordinatorService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6716c0001471ecb23830abc2de668d5dc9bb0fbb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCoordinatorService.java)|95.93%|:green_apple:|
|[BookingLimitService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6716c0001471ecb23830abc2de668d5dc9bb0fbb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingLimitService.java)|90.22%|:green_apple:|
|[InterviewerSlotValidator.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6716c0001471ecb23830abc2de668d5dc9bb0fbb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fvalidators%2FInterviewerSlotValidator.java)|88.89%|:green_apple:|
|[Booking.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6716c0001471ecb23830abc2de668d5dc9bb0fbb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|76.39%|:green_apple:|
|[BookingLimit.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6716c0001471ecb23830abc2de668d5dc9bb0fbb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBookingLimit.java)|71.43%|:green_apple:|
|[BookingDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6716c0001471ecb23830abc2de668d5dc9bb0fbb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingDto.java)|62.88%|:green_apple:|
|[InterviewerSlotDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6716c0001471ecb23830abc2de668d5dc9bb0fbb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerSlotDto.java)|57.91%|:green_apple:|
|[NotFoundException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/6716c0001471ecb23830abc2de668d5dc9bb0fbb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FNotFoundException.java)|44.59%|:green_apple:|

|Total Project Coverage|59.08%|:green_apple:|
|:-|:-:|:-:|

2022-11-13 16:37 UTC, Mo-og commented
|File|Coverage [79.65%]|:green_apple:|
|:-|:-:|:-:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ad2c97e8a709e4000da0985cced9da4471aae03d/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[WeekController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ad2c97e8a709e4000da0985cced9da4471aae03d/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FWeekController.java)|100%|:green_apple:|
|[SlotController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ad2c97e8a709e4000da0985cced9da4471aae03d/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FSlotController.java)|100%|:green_apple:|
|[WeekServiceImp.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ad2c97e8a709e4000da0985cced9da4471aae03d/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FWeekServiceImp.java)|100%|:green_apple:|
|[InterviewerService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ad2c97e8a709e4000da0985cced9da4471aae03d/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|100%|:green_apple:|
|[CoordinatorService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ad2c97e8a709e4000da0985cced9da4471aae03d/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCoordinatorService.java)|95.93%|:green_apple:|
|[BookingLimitService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ad2c97e8a709e4000da0985cced9da4471aae03d/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingLimitService.java)|90.22%|:green_apple:|
|[InterviewerSlotValidator.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ad2c97e8a709e4000da0985cced9da4471aae03d/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fvalidators%2FInterviewerSlotValidator.java)|88.89%|:green_apple:|
|[Booking.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ad2c97e8a709e4000da0985cced9da4471aae03d/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|76.39%|:green_apple:|
|[BookingLimit.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ad2c97e8a709e4000da0985cced9da4471aae03d/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBookingLimit.java)|71.43%|:green_apple:|
|[NotFoundException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ad2c97e8a709e4000da0985cced9da4471aae03d/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FNotFoundException.java)|67.57%|:green_apple:|
|[BookingDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ad2c97e8a709e4000da0985cced9da4471aae03d/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingDto.java)|62.88%|:green_apple:|
|[InterviewerSlotDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ad2c97e8a709e4000da0985cced9da4471aae03d/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerSlotDto.java)|57.91%|:green_apple:|

|Total Project Coverage|59.5%|:green_apple:|
|:-|:-:|:-:|

2022-11-13 16:39 UTC, Mo-og commented
|File|Coverage [80.37%]|:green_apple:|
|:-|:-:|:-:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/fc9a1008f14c1042f60817b811af8687e72cd05a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[WeekController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/fc9a1008f14c1042f60817b811af8687e72cd05a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FWeekController.java)|100%|:green_apple:|
|[SlotController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/fc9a1008f14c1042f60817b811af8687e72cd05a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FSlotController.java)|100%|:green_apple:|
|[WeekServiceImp.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/fc9a1008f14c1042f60817b811af8687e72cd05a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FWeekServiceImp.java)|100%|:green_apple:|
|[InterviewerService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/fc9a1008f14c1042f60817b811af8687e72cd05a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|100%|:green_apple:|
|[CoordinatorService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/fc9a1008f14c1042f60817b811af8687e72cd05a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCoordinatorService.java)|95.93%|:green_apple:|
|[BookingLimitService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/fc9a1008f14c1042f60817b811af8687e72cd05a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingLimitService.java)|90.22%|:green_apple:|
|[UserService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/fc9a1008f14c1042f60817b811af8687e72cd05a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|89.16%|:green_apple:|
|[InterviewerSlotValidator.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/fc9a1008f14c1042f60817b811af8687e72cd05a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fvalidators%2FInterviewerSlotValidator.java)|88.89%|:green_apple:|
|[NotFoundException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/fc9a1008f14c1042f60817b811af8687e72cd05a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FNotFoundException.java)|77.03%|:green_apple:|
|[Booking.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/fc9a1008f14c1042f60817b811af8687e72cd05a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|76.39%|:green_apple:|
|[BookingLimit.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/fc9a1008f14c1042f60817b811af8687e72cd05a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBookingLimit.java)|71.43%|:green_apple:|
|[BookingDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/fc9a1008f14c1042f60817b811af8687e72cd05a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingDto.java)|62.88%|:green_apple:|
|[InterviewerSlotDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/fc9a1008f14c1042f60817b811af8687e72cd05a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerSlotDto.java)|57.91%|:green_apple:|

|Total Project Coverage|59.63%|:green_apple:|
|:-|:-:|:-:|

2022-11-13 16:40 UTC, Mo-og commented
|File|Coverage [81.19%]|:green_apple:|
|:-|:-:|:-:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/014645fd9896e2234b260f90542865933db59ab4/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[NotFoundException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/014645fd9896e2234b260f90542865933db59ab4/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FNotFoundException.java)|100%|:green_apple:|
|[WeekController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/014645fd9896e2234b260f90542865933db59ab4/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FWeekController.java)|100%|:green_apple:|
|[SlotController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/014645fd9896e2234b260f90542865933db59ab4/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FSlotController.java)|100%|:green_apple:|
|[WeekServiceImp.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/014645fd9896e2234b260f90542865933db59ab4/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FWeekServiceImp.java)|100%|:green_apple:|
|[InterviewerService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/014645fd9896e2234b260f90542865933db59ab4/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|100%|:green_apple:|
|[CoordinatorService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/014645fd9896e2234b260f90542865933db59ab4/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCoordinatorService.java)|95.93%|:green_apple:|
|[BookingLimitService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/014645fd9896e2234b260f90542865933db59ab4/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingLimitService.java)|90.22%|:green_apple:|
|[UserService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/014645fd9896e2234b260f90542865933db59ab4/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|89.16%|:green_apple:|
|[InterviewerSlotValidator.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/014645fd9896e2234b260f90542865933db59ab4/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fvalidators%2FInterviewerSlotValidator.java)|88.89%|:green_apple:|
|[Booking.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/014645fd9896e2234b260f90542865933db59ab4/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|76.39%|:green_apple:|
|[BookingLimit.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/014645fd9896e2234b260f90542865933db59ab4/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBookingLimit.java)|71.43%|:green_apple:|
|[BookingDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/014645fd9896e2234b260f90542865933db59ab4/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingDto.java)|62.88%|:green_apple:|
|[InterviewerSlotDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/014645fd9896e2234b260f90542865933db59ab4/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerSlotDto.java)|57.91%|:green_apple:|

|Total Project Coverage|59.93%|:green_apple:|
|:-|:-:|:-:|

2022-11-13 16:46 UTC, Mo-og commented
|File|Coverage [81.19%]|:green_apple:|
|:-|:-:|:-:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/dc7e7a9002ebcf6005969510461e2afdadc6f681/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[NotFoundException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/dc7e7a9002ebcf6005969510461e2afdadc6f681/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FNotFoundException.java)|100%|:green_apple:|
|[WeekController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/dc7e7a9002ebcf6005969510461e2afdadc6f681/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FWeekController.java)|100%|:green_apple:|
|[SlotController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/dc7e7a9002ebcf6005969510461e2afdadc6f681/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FSlotController.java)|100%|:green_apple:|
|[WeekServiceImp.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/dc7e7a9002ebcf6005969510461e2afdadc6f681/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FWeekServiceImp.java)|100%|:green_apple:|
|[InterviewerService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/dc7e7a9002ebcf6005969510461e2afdadc6f681/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|100%|:green_apple:|
|[CoordinatorService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/dc7e7a9002ebcf6005969510461e2afdadc6f681/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCoordinatorService.java)|95.93%|:green_apple:|
|[BookingLimitService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/dc7e7a9002ebcf6005969510461e2afdadc6f681/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingLimitService.java)|90.22%|:green_apple:|
|[UserService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/dc7e7a9002ebcf6005969510461e2afdadc6f681/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|89.16%|:green_apple:|
|[InterviewerSlotValidator.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/dc7e7a9002ebcf6005969510461e2afdadc6f681/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fvalidators%2FInterviewerSlotValidator.java)|88.89%|:green_apple:|
|[Booking.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/dc7e7a9002ebcf6005969510461e2afdadc6f681/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|76.39%|:green_apple:|
|[BookingLimit.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/dc7e7a9002ebcf6005969510461e2afdadc6f681/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBookingLimit.java)|71.43%|:green_apple:|
|[BookingDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/dc7e7a9002ebcf6005969510461e2afdadc6f681/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingDto.java)|62.88%|:green_apple:|
|[InterviewerSlotDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/dc7e7a9002ebcf6005969510461e2afdadc6f681/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerSlotDto.java)|57.91%|:green_apple:|

|Total Project Coverage|59.64%|:green_apple:|
|:-|:-:|:-:|

2022-11-18 01:29 UTC, olesiayakovenko requested changes

2022-11-18 01:29 UTC, olesiayakovenko commented on src/main/java/com/intellias/intellistart/interviewplanning/services/WeekServiceImp.java
> +    return LocalDate.now().getDayOfWeek();
To get the current date, use this.getCurrentDate() method with the specified time zone.

2022-11-18 01:29 UTC, olesiayakovenko commented on src/main/java/com/intellias/intellistart/interviewplanning/validators/InterviewerSlotValidator.java
> +    var now = weekService.getNowDay();
Perhaps var should be replaced with DayOfWeek.

2022-11-18 01:29 UTC, olesiayakovenko commented on src/main/java/com/intellias/intellistart/interviewplanning/validators/InterviewerSlotValidator.java
> +@Component
Why did you decide to add the Component annotation?

2022-11-18 01:32 UTC, olesiayakovenko approved these changes

2022-11-19 14:23 UTC, Mo-og commented
|File|Coverage [81.22%]|:green_apple:|
|:-|:-:|:-:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/568223fb00ea677353aafde5a1810d2ffde1bc4f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[NotFoundException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/568223fb00ea677353aafde5a1810d2ffde1bc4f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FNotFoundException.java)|100%|:green_apple:|
|[WeekController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/568223fb00ea677353aafde5a1810d2ffde1bc4f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FWeekController.java)|100%|:green_apple:|
|[SlotController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/568223fb00ea677353aafde5a1810d2ffde1bc4f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FSlotController.java)|100%|:green_apple:|
|[WeekServiceImp.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/568223fb00ea677353aafde5a1810d2ffde1bc4f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FWeekServiceImp.java)|100%|:green_apple:|
|[InterviewerService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/568223fb00ea677353aafde5a1810d2ffde1bc4f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|100%|:green_apple:|
|[CoordinatorService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/568223fb00ea677353aafde5a1810d2ffde1bc4f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCoordinatorService.java)|95.93%|:green_apple:|
|[BookingLimitService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/568223fb00ea677353aafde5a1810d2ffde1bc4f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingLimitService.java)|90.22%|:green_apple:|
|[UserService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/568223fb00ea677353aafde5a1810d2ffde1bc4f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|89.16%|:green_apple:|
|[InterviewerSlotValidator.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/568223fb00ea677353aafde5a1810d2ffde1bc4f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fvalidators%2FInterviewerSlotValidator.java)|88.89%|:green_apple:|
|[Booking.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/568223fb00ea677353aafde5a1810d2ffde1bc4f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|76.39%|:green_apple:|
|[BookingLimit.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/568223fb00ea677353aafde5a1810d2ffde1bc4f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBookingLimit.java)|71.43%|:green_apple:|
|[BookingDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/568223fb00ea677353aafde5a1810d2ffde1bc4f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingDto.java)|62.88%|:green_apple:|
|[InterviewerSlotDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/568223fb00ea677353aafde5a1810d2ffde1bc4f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerSlotDto.java)|57.91%|:green_apple:|

|Total Project Coverage|59.67%|:green_apple:|
|:-|:-:|:-:|

2022-11-19 15:33 UTC, merged