75 add validation of intervieweridslotid n
Mo-og/intellistart-java-2022-debuggers pull request #89
Opened 2022-11-16 15:57 UTC by holeksii

2022-11-16 16:18 UTC, Mo-og commented
|File|Coverage [87.23%]|:green_apple:|
|:-|:-:|:-:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ff3d7d03bf806de2642cb276bd60f02b99fad6c2/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[PeriodValidator.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ff3d7d03bf806de2642cb276bd60f02b99fad6c2/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fvalidators%2FPeriodValidator.java)|100%|:green_apple:|
|[CandidateService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ff3d7d03bf806de2642cb276bd60f02b99fad6c2/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCandidateService.java)|100%|:green_apple:|
|[InterviewerService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ff3d7d03bf806de2642cb276bd60f02b99fad6c2/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|95.86%|:green_apple:|
|[BookingService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ff3d7d03bf806de2642cb276bd60f02b99fad6c2/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingService.java)|94.29%|:green_apple:|
|[InterviewerTimeSlot.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ff3d7d03bf806de2642cb276bd60f02b99fad6c2/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewerTimeSlot.java)|87.94%|:green_apple:|
|[InterviewerSlotValidator.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ff3d7d03bf806de2642cb276bd60f02b99fad6c2/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fvalidators%2FInterviewerSlotValidator.java)|81.48%|:green_apple:|
|[InvalidInputException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ff3d7d03bf806de2642cb276bd60f02b99fad6c2/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidInputException.java)|80.46%|:green_apple:|
|[Booking.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ff3d7d03bf806de2642cb276bd60f02b99fad6c2/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|67.74%|:green_apple:|
|[CandidateTimeSlot.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/ff3d7d03bf806de2642cb276bd60f02b99fad6c2/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidateTimeSlot.java)|66.67%|:green_apple:|

|Total Project Coverage|56.56%|:green_apple:|
|:-|:-:|:-:|

2022-11-17 18:34 UTC, olesiayakovenko requested changes

2022-11-17 18:34 UTC, olesiayakovenko commented on src/main/java/com/intellias/intellistart/interviewplanning/exceptions/InvalidInputException.java
> +        String.format(": slot with id \"%d\" do not belongs to interviewer with id \"%d\"",
Remove all unnecessary colons ":" and slashes "\\".

Now the response looks something like this:
![image](https://user-images.githubusercontent.com/31793743/202523599-932b88db-629e-4340-b543-24a0cfdd800b.png)

2022-11-17 18:34 UTC, olesiayakovenko commented on src/main/java/com/intellias/intellistart/interviewplanning/validators/PeriodValidator.java
> +        && Math.abs(to.getMinute() - from.getMinute()) % 30 == 0
You should check the division by 30 separately for **from** and **to**, not after subtraction. Because the case **from 9:02** **to 10:32** passes validation.

Now the response looks something like this:
![image](https://user-images.githubusercontent.com/31793743/202528101-8007f9d5-68e5-4529-99e0-8fdea51da9f0.png)

Must follow the requirements:
![image](https://user-images.githubusercontent.com/31793743/202528555-a9582aef-5dd3-45fa-b794-4296b2f01acf.png)

2022-11-19 14:05 UTC, olesiayakovenko commented on src/main/java/com/intellias/intellistart/interviewplanning/validators/InterviewerSlotValidator.java
>      } else if (interviewerTimeSlot.getWeekNum() != WeekService.getNextWeekNum()) {
Interviewer can create or update time slots for **_next week_**, but Coordinator can update any Interviewer's time slot **_(next week or current week)_**.

2022-11-22 17:26 UTC, closed without merging